# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_simulation_cpp <- function(num_agents, n_simulations, methods, stages, stages_name, p_prior, ps_theory, adoption_efficacy, non_adoption_efficacy) {
    .Call(`_doipkg_run_simulation_cpp`, num_agents, n_simulations, methods, stages, stages_name, p_prior, ps_theory, adoption_efficacy, non_adoption_efficacy)
}

